# fly.toml app configuration file generated for turbojugend on 2025-03-28T06:41:08Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'turbojugend'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
